module Zendesk2::HelpCenter; end

require 'zendesk2/help_center/create_help_center_article'
require 'zendesk2/help_center/create_help_center_category'
require 'zendesk2/help_center/create_help_center_section'
require 'zendesk2/help_center/destroy_help_center_article'
require 'zendesk2/help_center/destroy_help_center_category'
require 'zendesk2/help_center/destroy_help_center_section'
require 'zendesk2/help_center/get_help_center_article'
require 'zendesk2/help_center/get_help_center_articles'
require 'zendesk2/help_center/get_help_center_categories'
require 'zendesk2/help_center/get_help_center_categories_articles'
require 'zendesk2/help_center/get_help_center_categories_sections'
require 'zendesk2/help_center/get_help_center_category'
require 'zendesk2/help_center/get_help_center_section'
require 'zendesk2/help_center/get_help_center_sections'
require 'zendesk2/help_center/get_help_center_sections_articles'
require 'zendesk2/help_center/search_help_center_articles'
require 'zendesk2/help_center/update_help_center_article'
require 'zendesk2/help_center/update_help_center_category'
require 'zendesk2/help_center/update_help_center_section'

require 'zendesk2/help_center/article'
require 'zendesk2/help_center/category'
require 'zendesk2/help_center/section'

require 'zendesk2/help_center/articles'
require 'zendesk2/help_center/categories'
require 'zendesk2/help_center/sections'
