# frozen_string_literal: true
module Zendesk2::HelpCenter; end

require 'zendesk2/help_center/translation_source'
require 'zendesk2/help_center/subscription_request'

require 'zendesk2/help_center/create_help_center_article'
require 'zendesk2/help_center/create_help_center_category'
require 'zendesk2/help_center/create_help_center_post'
require 'zendesk2/help_center/create_help_center_section'
require 'zendesk2/help_center/create_help_center_subscription'
require 'zendesk2/help_center/create_help_center_topic'
require 'zendesk2/help_center/create_help_center_translation'
require 'zendesk2/help_center/destroy_help_center_article'
require 'zendesk2/help_center/destroy_help_center_category'
require 'zendesk2/help_center/destroy_help_center_post'
require 'zendesk2/help_center/destroy_help_center_section'
require 'zendesk2/help_center/destroy_help_center_topic'
require 'zendesk2/help_center/destroy_help_center_translation'
require 'zendesk2/help_center/get_help_center_access_policy'
require 'zendesk2/help_center/get_help_center_article'
require 'zendesk2/help_center/get_help_center_articles'
require 'zendesk2/help_center/get_help_center_categories'
require 'zendesk2/help_center/get_help_center_categories_articles'
require 'zendesk2/help_center/get_help_center_categories_sections'
require 'zendesk2/help_center/get_help_center_category'
require 'zendesk2/help_center/get_help_center_post'
require 'zendesk2/help_center/get_help_center_posts'
require 'zendesk2/help_center/get_help_center_section'
require 'zendesk2/help_center/get_help_center_sections'
require 'zendesk2/help_center/get_help_center_sections_articles'
require 'zendesk2/help_center/get_help_center_subscription'
require 'zendesk2/help_center/get_help_center_subscriptions'
require 'zendesk2/help_center/get_help_center_topic'
require 'zendesk2/help_center/get_help_center_topics'
require 'zendesk2/help_center/get_help_center_translation'
require 'zendesk2/help_center/get_help_center_translations'
require 'zendesk2/help_center/search_help_center_articles'
require 'zendesk2/help_center/update_help_center_access_policy'
require 'zendesk2/help_center/update_help_center_article'
require 'zendesk2/help_center/update_help_center_category'
require 'zendesk2/help_center/update_help_center_post'
require 'zendesk2/help_center/update_help_center_section'
require 'zendesk2/help_center/update_help_center_topic'
require 'zendesk2/help_center/update_help_center_subscription'
require 'zendesk2/help_center/update_help_center_translation'

require 'zendesk2/help_center/access_policy'
require 'zendesk2/help_center/article'
require 'zendesk2/help_center/category'
require 'zendesk2/help_center/post'
require 'zendesk2/help_center/section'
require 'zendesk2/help_center/subscription'
require 'zendesk2/help_center/topic'
require 'zendesk2/help_center/translation'

require 'zendesk2/help_center/articles'
require 'zendesk2/help_center/categories'
require 'zendesk2/help_center/posts'
require 'zendesk2/help_center/sections'
require 'zendesk2/help_center/subscriptions'
require 'zendesk2/help_center/topics'
require 'zendesk2/help_center/translations'
